### ISSUE TITLE
The auto-improve tool of the code start automatically 

### ISSUE THREAD

**Issue by ji-ze** [dkriegner/micro-flakes#29]
If I strart manually, I get:
![Screenshot_20231214_163317.jpg](https://github.com/dkriegner/micro-flakes/assets/44098973/b45aaee6-3815-48fe-bac7-e93d171a9ff2)

![Screenshot_20231214_163321.jpg](https://github.com/dkriegner/micro-flakes/assets/44098973/d8f60ac4-be88-48f4-813f-d54c317eb5e7)

**Comment by dkriegner** [comment]
Hi Jirka,

This fails because it tries to fetch the branch I have already deleted. I
am afraid its not easy to run this manual since it is not set up like this.
I believe it would be easy to set it up to run on your computer. You only
need to pip install some packages and call the commands which are in the
yml file.

**Comment by ji-ze** [comment]
Hi Dominik,
it is solved. Use `-q True`
